### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'dist_params'

### ISSUE THREAD

**Issue by wmkai** [hustvl/TopFormer#3]
Hello, Thanks for providing such a great repo. But I encountered an error when run 
`bash tools/dist_train.sh local_configs/topformer/topformer_base.py 8 --work-dir /path/to/save/checkpoint`
Details are as follows:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/39148461/163945508-ac4efe7c-2a54-495a-8d6b-aa3487ea63dc.png">

**Comment by mulinmeng** [comment]
The 'topformer_base.py' contains only the settings of 'model', not the settings of 'datasets', 'schedules', etc. You can run `bash tools/dist_train.sh topformer_base_512x512_160k_2x8_ade20k.py 8 --work-dir /path/to/save/checkpoint`.  If you have any other questions, feel free to ask under this issue.

**Comment by mulinmeng** [comment]
> Hello, Thanks for providing such a great repo. But I encountered an error when run `bash tools/dist_train.sh local_configs/topformer/topformer_base.py 8 --work-dir /path/to/save/checkpoint` Details are as follows: <img alt="image" width="757" src="https://user-images.githubusercontent.com/39148461/163945508-ac4efe7c-2a54-495a-8d6b-aa3487ea63dc.png">

The 'topformer_base.py' contains only the settings of 'model', not the settings of 'datasets', 'schedules', etc. You can run bash tools/dist_train.sh topformer_base_512x512_160k_2x8_ade20k.py 8 --work-dir /path/to/save/checkpoint. If you have any other questions, feel free to ask under this issue.

**Comment by wmkai** [comment]
> > Hello, Thanks for providing such a great repo. But I encountered an error when run `bash tools/dist_train.sh local_configs/topformer/topformer_base.py 8 --work-dir /path/to/save/checkpoint` Details are as follows: <img alt="image" width="757" src="https://user-images.githubusercontent.com/39148461/163945508-ac4efe7c-2a54-495a-8d6b-aa3487ea63dc.png">
> 
> The 'topformer_base.py' contains only the settings of 'model', not the settings of 'datasets', 'schedules', etc. You can run bash tools/dist_train.sh topformer_base_512x512_160k_2x8_ade20k.py 8 --work-dir /path/to/save/checkpoint. If you have any other questions, feel free to ask under this issue.

thank you! it works.

**Comment by yukaizhou** [comment]
root@workspace:/dfs/data/code_python/detection_2d/mmdetection# CUDA_VISIBLE_DEVICES=1 tools/dist_train.sh configs/deformable_detr/deformable_detr_r50_16x2_50e_coco.py 1
Traceback (most recent call last):
  File "tools/train.py", line 244, in <module>
    main()
  File "tools/train.py", line 172, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/mmcv/utils/config.py", line 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dist_params'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2441) of binary: /dfs/data/anaconda/envs/deformable_detr/bin/python
Traceback (most recent call last):
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/dfs/data/anaconda/envs/deformable_detr/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-09_15:03:20
  host      : workspace
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2441)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
